In [88]:
import pandas as pd
import pandas_datareader as pdr
import yfinance as yf
import datetime
import time
end_date = datetime.datetime.now()
start_date = "2019-01-01"
symbols = ['AEM.TO', 'AQN.TO', 'ATD.TO', 'BCE.TO', 'BMO.TO', 'BNS.TO', 'ABX.TO', 'BAM-A.TO', 'BIP-UN.TO', 'CAE.TO', 'CCL-B.TO', 'GIB-A.TO', 'CCO.TO', 'CAR-UN.TO', 'CM.TO', 'CNR.TO', 'CNQ.TO', 'CP.TO', 'CTC-A.TO', 'CVE.TO', 'CSU.TO', 'DOL.TO', 'EMA.TO', 'ENB.TO', 'FM.TO', 'FSV.TO', 'FTS.TO', 'FNV.TO', 'WN.TO', 'GIL.TO', 'IMO.TO', 'IFC.TO', 'H.TO', 'K.TO', 'L.TO', 'MG.TO', 'MFC.TO', 'MRU.TO', 'NA.TO', 'NTR.TO', 'OTEX.TO', 'PPL.TO', 'POW.TO', 'QSR.TO', 'RCI-B.TO', 'RY.TO', 'SNC.TO', 'SAP.TO', 'SJR-B.TO', 'SHOP.TO', 'SLF.TO', 'SU.TO', 'TRP.TO', 'TECK-B.TO', 'T.TO', 'TRI.TO', 'TD.TO', 'TOU.TO', 'WCN.TO', 'WPM.TO']

In [102]:
print(yf.__version__)
def get_data(symbols, name):
    print("Requesting information for " + name)
    print(start_date, end_date)
    df = yf.download(tickers = symbols, period = '2y', threads=True)['Close']
    return df
df = get_data(symbols, 'r')

#filter_five_days("d")

0.2.3
Requesting information for r
2019-01-01 2023-01-11 15:41:27.588685
[*********************100%***********************]  60 of 60 completed

In [112]:
def filter_five_days(df):
    end_date= datetime.datetime.now() #- datetime.timedelta(1)
    start_date= pd.to_datetime(end_date-datetime.timedelta(days=5))
    week_no = end_date.weekday()
    print(week_no)
    e = str(end_date)[:10]
    s = str(start_date)[:10]
    df1 = pd.DataFrame(columns=['Symbol', 'Five'])
    for column in df:
        percent_change = (df.loc[e,column] - df.loc[s, column])/df.loc[s, column]*100
        df1.loc[len(df1)] = [column, percent_change]
       # print(column, 'Percent change',percent_change)
    return df1
        
filtered = filter_five_days(df)
a = filtered.sort_values(by=['Five'],ascending=False)
a.head()

2

       Symbol      Five
49     SNC.TO  8.416597
25     FSV.TO  6.446157
10  CAR-UN.TO  6.079379
28     GIL.TO  4.510503
12     CCO.TO  3.714985

In [113]:
def filter_ten_days(df):
    end_date= datetime.datetime.now() - datetime.timedelta(1)
    start_date= end_date-datetime.timedelta(10)
    end_week_no = end_date.weekday()
    start_week_no = start_date.weekday()
    if end_week_no > 6:
        end_date - datetime.timedelta(2)
    elif start_week_no > 6:
        start_date = datetime.timedelta(2)    
    e = str(end_date)[:10]
    s = str(start_date)[:10]
    df1 = pd.DataFrame(columns=['Symbol', 'Ten'])
    try:
        for column in df:
            #print(column, 'Percent change', (df.loc[e,column] - df.loc[s, column])/df.loc[s, column]*100)
            percent_change = (df.loc[e,column] - df.loc[s, column])/df.loc[s, column]*100
            df1.loc[len(df1)] = [column, percent_change]
    
    except:
        start_date = start_date - datetime.timedelta(1)
        s = str(start_date)[:10]
        for column in df:
            #print(column, 'Percent change', (df.loc[e,column] - df.loc[s, column])/df.loc[s, column]*100)
            percent_change = (df.loc[e,column] - df.loc[s, column])/df.loc[s, column]*100
            df1.loc[len(df1)] = [column, percent_change]
    
    return df1
        
filtered_ten = filter_ten_days(df)
b = filtered_ten.sort_values(by=['Ten'],ascending=False)
b.head()

    Symbol        Ten
49  SNC.TO  15.046103
32    K.TO  12.318838
0   ABX.TO  12.279192
12  CCO.TO  10.752692
59  WPM.TO  10.321359

In [114]:
def filter_twenty_days(df):
    end_date= datetime.datetime.now() - datetime.timedelta(1)
    start_date= end_date-datetime.timedelta(20)
    end_week_no = end_date.weekday()
    start_week_no = start_date.weekday()
    if end_week_no > 6:
        end_date - datetime.timedelta(2)
    elif start_week_no > 6:
        start_date = datetime.timedelta(2)    
    e = str(end_date)[:10]
    s = str(start_date)[:10]
    df1 = pd.DataFrame(columns=['Symbol', 'Twenty'])
    try:
        for column in df:
            #print(column, 'Percent change', (df.loc[e,column] - df.loc[s, column])/df.loc[s, column]*100)
            percent_change = (df.loc[e,column] - df.loc[s, column])/df.loc[s, column]*100
            df1.loc[len(df1)] = [column, percent_change]
    
    except:
        start_date = start_date - datetime.timedelta(1)
        s = str(start_date)[:10]
        for column in df:
            #print(column, 'Percent change', (df.loc[e,column] - df.loc[s, column])/df.loc[s, column]*100)
            percent_change = (df.loc[e,column] - df.loc[s, column])/df.loc[s, column]*100
            df1.loc[len(df1)] = [column, percent_change]
    return df1
        
filtered_twenty = filter_twenty_days(df)
c = filtered_twenty.sort_values(by=['Twenty'],ascending=False)
c.head()

    Symbol     Twenty
49  SNC.TO  17.659669
12  CCO.TO  13.036255
23   FM.TO  11.898738
0   ABX.TO   9.541818
32    K.TO   7.638881

In [116]:
def filter_year(df):
    end_date= datetime.datetime.now() - datetime.timedelta(1)
    start_date= end_date-datetime.timedelta(365)
    end_week_no = end_date.weekday()
    start_week_no = start_date.weekday()
    if end_week_no > 6:
        end_date - datetime.timedelta(2)
    elif start_week_no > 6:
        start_date = datetime.timedelta(2)    
    e = str(end_date)[:10]
    s = str(start_date)[:10]
    df1 = pd.DataFrame(columns=['Symbol', 'YTD CHANGE'])
    try:
        for column in df:
            #print(column, 'Percent change', (df.loc[e,column] - df.loc[s, column])/df.loc[s, column]*100)
            percent_change = (df.loc[e,column] - df.loc[s, column])/df.loc[s, column]*100
            df1.loc[len(df1)] = [column, percent_change]
    
    except:
        start_date = start_date - datetime.timedelta(1)
        s = str(start_date)[:10]
        for column in df:
            #print(column, 'Percent change', (df.loc[e,column] - df.loc[s, column])/df.loc[s, column]*100)
            percent_change = (df.loc[e,column] - df.loc[s, column])/df.loc[s, column]*100
            df1.loc[len(df1)] = [column, percent_change]
    
    return df1
        
filtered_year = filter_year(df)
filtered_year.sort_values(by=['YTD CHANGE'],ascending=False)

       Symbol  YTD CHANGE
54     TOU.TO   46.171638
19     CVE.TO   46.109180
53  TECK-B.TO   34.337043
20     DOL.TO   31.666673
31     IMO.TO   31.597293
14     CNQ.TO   27.295511
50      SU.TO   23.583509
3      ATD.TO   23.169293
30     IFC.TO   21.124966
58      WN.TO   21.044171
42     QSR.TO   20.032528
41     PPL.TO   18.329941
45     SAP.TO   17.867918
33       L.TO   17.226106
59     WPM.TO   17.071218
24     FNV.TO   15.994723
12     CCO.TO   15.415962
38     NTR.TO   14.791811
29       H.TO   13.910017
1      AEM.TO   13.461825
36     MRU.TO   10.584374
0      ABX.TO   10.470535
55     TRI.TO   10.408521
57     WCN.TO    8.654616
27   GIB-A.TO    8.528381
16      CP.TO    6.816530
22     ENB.TO    6.604687
15     CNR.TO    5.007723
17     CSU.TO    3.610211
43   RCI-B.TO    2.606022
47   SJR-B.TO    1.310616
23      FM.TO   -0.193547
34     MFC.TO   -3.355438
37      NA.TO   -3.573597
5      BCE.TO   -6.497262
26     FTS.TO   -6.590067
44      RY.TO   -6.756476
49     SNC.TO   -7.978542
51       T.TO   -8.446404
11   CCL-B.TO   -8.960245
6   BIP-UN.TO  -10.709540
7      BMO.TO  -10.765467
48     SLF.TO  -11.227084
32       K.TO  -11.931820
56     TRP.TO  -12.213494
52      TD.TO  -13.767174
21     EMA.TO  -14.290421
9      CAE.TO  -14.294637
18   CTC-A.TO  -16.405434
25     FSV.TO  -18.062035
40     POW.TO  -18.837490
10  CAR-UN.TO  -20.901277
35      MG.TO  -24.200407
8      BNS.TO  -25.646101
28     GIL.TO  -25.702355
13      CM.TO  -27.505410
39    OTEX.TO  -28.806302
4    BAM-A.TO  -37.045802
2      AQN.TO  -45.352114
46    SHOP.TO  -65.820254

In [111]:
a.join(b.set_index('Symbol'), on='Symbol').join(c.set_index('Symbol'), on='Symbol')

       Symbol      Five        Ten     Twenty
49     SNC.TO  8.416597  15.046103  17.659669
25     FSV.TO  6.446157   8.015203   5.445982
10  CAR-UN.TO  6.079379   5.693534   7.532777
28     GIL.TO  4.510503   5.555549   6.214385
12     CCO.TO  3.714985  10.752692  13.036255
39    OTEX.TO  3.696924   3.614160   4.237710
6   BIP-UN.TO  3.230909   6.819267   3.559873
23      FM.TO  3.116623   9.367266  11.898738
37      NA.TO  2.969034   4.406441   2.474452
24     FNV.TO  2.947746   4.751579   5.437095
53  TECK-B.TO  2.943947   3.752203   1.027595
9      CAE.TO  2.835822   4.849173   3.116785
56     TRP.TO  2.820794   1.463507  -0.363836
45     SAP.TO  2.805374   4.892600   5.522209
2      AQN.TO  2.795036   9.977326   6.010931
40     POW.TO  2.648020   7.409729   3.760988
14     CNQ.TO  2.387775  -1.090570  -0.694347
41     PPL.TO  2.308868   1.131420   0.889950
34     MFC.TO  1.904373   2.567291   1.350245
17     CSU.TO  1.709098   6.083374   4.572630
22     ENB.TO  1.707676   4.006052   2.974743
44      RY.TO  1.702063   4.399050   3.287476
11   CCL-B.TO  1.570416   2.939144   2.425597
18   CTC-A.TO  1.494913   7.420495   6.906743
26     FTS.TO  1.269037   2.030267   0.582241
27   GIB-A.TO  1.229582  -1.867878  -2.866597
13      CM.TO  1.166902   3.943765   1.952006
54     TOU.TO  0.877055  -7.508784 -11.523382
21     EMA.TO  0.840976   0.483092  -0.459421
7      BMO.TO  0.625632   4.068154   3.687760
8      BNS.TO  0.617653   1.914387   2.657152
35      MG.TO  0.567566   7.809627   6.562707
51       T.TO  0.518132   3.291239   0.558866
3      ATD.TO  0.484886   5.159663   1.756380
0      ABX.TO  0.448867  12.279192   9.541818
32       K.TO  0.325733  12.318838   7.638881
58      WN.TO  0.311648   3.095420  -0.178673
42     QSR.TO  0.283222   1.130522  -1.215844
47   SJR-B.TO  0.155122  -0.922832   6.945219
50      SU.TO  0.071155  -3.003495  -1.489716
48     SLF.TO  0.062727   0.143198  -0.788146
52      TD.TO  0.011572  -1.904868  -2.383653
43   RCI-B.TO -0.140669   0.031561   3.832924
59     WPM.TO -0.189004  10.321359   7.141545
15     CNR.TO -0.212847   1.429994  -1.181172
55     TRI.TO -0.229461   0.608563   1.694913
29       H.TO -0.502585  -0.882271  -1.883184
16      CP.TO -0.585301   1.674099  -0.513714
36     MRU.TO -0.668360  -1.053756  -3.007326
57     WCN.TO -0.907620  -1.860930  -3.357838
5      BCE.TO -0.973707   3.294670   2.604778
30     IFC.TO -1.286218   2.195885   0.181060
1      AEM.TO -1.426262   5.415005   4.244549
20     DOL.TO -1.495415   2.752873   1.193880
46    SHOP.TO -1.553673   4.254414  -0.507511
31     IMO.TO -1.926040  -2.683846  -1.745253
33       L.TO -2.237753  -0.526232  -2.870895
19     CVE.TO -2.246754  -4.225354  -2.969535
38     NTR.TO -4.111369   0.961057  -1.011701
4    BAM-A.TO       NaN   6.200092   5.753047